/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CurriculoRouteImport } from './routes/curriculo'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as ApiPublicCurriculoRouteImport } from './routes/api/public/curriculo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculoRoute = CurriculoRouteImport.update({
  id: '/curriculo',
  path: '/curriculo',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCurriculoRoute = ApiPublicCurriculoRouteImport.update({
  id: '/api/public/curriculo',
  path: '/api/public/curriculo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/curriculo': typeof CurriculoRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/api/public/curriculo': typeof ApiPublicCurriculoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/curriculo': typeof CurriculoRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/api/public/curriculo': typeof ApiPublicCurriculoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/curriculo': typeof CurriculoRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/api/public/curriculo': typeof ApiPublicCurriculoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/curriculo'
    | '/sobre'
    | '/blog/$slug'
    | '/projetos/$slug'
    | '/blog/'
    | '/projetos/'
    | '/api/public/curriculo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/curriculo'
    | '/sobre'
    | '/blog/$slug'
    | '/projetos/$slug'
    | '/blog'
    | '/projetos'
    | '/api/public/curriculo'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/curriculo'
    | '/sobre'
    | '/blog/$slug'
    | '/projetos/$slug'
    | '/blog/'
    | '/projetos/'
    | '/api/public/curriculo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  CurriculoRoute: typeof CurriculoRoute
  SobreRoute: typeof SobreRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  ApiPublicCurriculoRoute: typeof ApiPublicCurriculoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculo': {
      id: '/curriculo'
      path: '/curriculo'
      fullPath: '/curriculo'
      preLoaderRoute: typeof CurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/curriculo': {
      id: '/api/public/curriculo'
      path: '/api/public/curriculo'
      fullPath: '/api/public/curriculo'
      preLoaderRoute: typeof ApiPublicCurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  CurriculoRoute: CurriculoRoute,
  SobreRoute: SobreRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  ApiPublicCurriculoRoute: ApiPublicCurriculoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
